version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  dev_cli:
    build:
      context: .
    command: jupyter notebook --allow-root --no-browser --ip 0.0.0.0
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - .:/app:cached
